In [1]:
import numpy as np

In [2]:
l1 = [1,2,3]

v1 = np.array([10,20,5])
v2 = np.array([5,5,10])
print(v1.dot(v2))
print(v2)
print(v1.ndim)
print(v1.shape)

200
[ 5  5 10]
1
(3,)


In [3]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m1)
print("=======================")
m2 = np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(m2)
print("=======================")
print("==========operations=============")
print(m1.dot(m2))   

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
==========operations=============
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [4]:
class student:
    
    def __init__(self,name):
        self.name = name
    @property
    def get_info(self):
        return f"my name is {self.name}"

In [6]:
s1 = student("sara")
s1.get_info


'my name is sara'

In [7]:
m1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [8]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [10]:
vec = np.array([1,2,3,4])
mat = vec[:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [11]:
class C:
    x = 3
o1 = C()

In [12]:
mat = np.array([[3,1,3],
               ["5",0,6],
               [7,8,9]])

In [13]:
f_mat = mat.astype(float)
print(f_mat.dtype)
f_mat

float64


array([[3., 1., 3.],
       [5., 0., 6.],
       [7., 8., 9.]])