In [1]:
pip install tensorflow

  Using cached tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached wrapt-2.1.2-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
  Using cached grpcio-1.80.0-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
  Using cached keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached h5py-3.14.0-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
  Using cached m


[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tensorflow as tf

In [3]:
x = tf.constant([[5,2],[1,3]]) # enter as a constant values
x   #in tensor format 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [1, 3]], dtype=int32)>

In [4]:
tf.random.normal(shape=(2,2),mean=0.,stddev=1.)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.2024511,  0.4614255],
       [-1.8141325,  1.2983837]], dtype=float32)>

In [5]:
init_val = tf.random.normal(shape=(2,2))
a = tf.Variable(init_val)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.1224648,  1.5674331],
       [-1.0088189, -1.9259337]], dtype=float32)>


In [6]:
a = tf.random.normal(shape=(2,2))
b = a = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
print(d)

tf.Tensor(
[[0.29841158 0.57348734]
 [4.722033   0.04456095]], shape=(2, 2), dtype=float32)


In [7]:
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv